GITHUB_URL = 'https://api.github.com'
GITHUB_USER_URL = GITHUB_URL + '/user'
GITHUB_REPO_URL = GITHUB_URL + '/repos/{owner}/{repo}'
GITHUB_USER_REPOS_URL = GITHUB_USER_URL + '/repos'
GITHUB_REPO_BRANCHES_URL = GITHUB_REPO_URL + "/branches"
GITHUB_REPO_PULLS_URL = GITHUB_REPO_URL + "/pulls"
GITHUB_REPO_PULLS_NUM_URL = GITHUB_REPO_PULLS_URL + "/{pull_numb}"
GITHUB_REPO_PULLS_NUM_REVIEWS_URL = GITHUB_REPO_PULLS_NUM_URL + "/reviews"
